message:
  time: '&name &fset &2&world &fto &period.'
  ban:
    kick: ''
    temp: ''
    perm: ''
  platform:
    created: '&2Platform Created.'
    toggled: '&2Platform Toggled (&mode).'
  gamemode:
    self: '&fGamemode set to &gamemode'
    other: '&fGamemode toggled for &target'
  location:
    pos:
      self: '&3World: &2&world &3X: &f&x &3Y: &f&y &3Z: &f&z'
      other: ''
    world:
      self: '&2You are in&f: &7&world'
      other: '&name is in&f: &7&world'
  who:
    all: '&aOnline players &c&online &f: &list'
    single: ''
    info: ''
    