message:
  time:
    dawn: $1 set $2 to $3.
    day: $1 set $2 to $3.
    noon: $1 set $2 to $3.
    dusk: $1 set $2 to $3.
    night: $1 set $2 to $3.
  ban:
    kick:
    temp:
    perm:
  platform:
    created:
    toggled:
  gamemode:
    self:
    other:
  location:
    pos:
      self:
      other:
    world:
      self:
      other:
  who:
    all:
    single:
    info:
    