name: Froggles
description: a whole pile o'shite
version: 1.2.23
main: com.frogman786.froggles.Froggles
depend: [Vault]
commands:
  pmsdebug:
    description: pms reply debug command
  cfgdebug:
    description: cfg debug command
  trackdebug:
    description: tracking debug
  dawn:
    description: makes dawn
  day:
    description: makes day
  noon:
    description: makes noon
  dusk:
    description: makes dusk
  night:
    description: makes night
  who:
    description: who is online
  gm:
    description: gamemode toggle
  platform:
    description: creates a block of glass below your feet
  promo:
    description: used to handle rank giving/taking
  world:
    description: used to find what world a player is in
  pos:
    description: /pos
  spleeflayer:
    description: used to make a sand layer for spleef
  cuboid:
    description: used to make a solid cuboid of any material
  me:
    description: same as default but with colour
  pms:
    description: message command
  r:
    description: message command
  track:
    description: tracks a player with compass
  untrack:
    description: untracks a player
  announce:
    description: sends a formatted global message
  announcepromo:
    description: sends a formatted global message for promos
  rainbowtext:
    description: send a formatted message for fun
  colourcodes:
    description: sends you a reply with the standard colourcodes for minecraft
  zombiesafety:
    description: protects zombies (duh)
  frogcommand:
    description: sets a toggle switch for commandblocks
  gamespawn:
    description: sets a bedspawn location
  randomchest:
    description: for spawning random chests in survival games
  chatfilter:
    description: standard command for the filter
  runcheck:
    description: for tommy
  fakequit:
    description: faking a quit
  fakejoin:
    description: faking a join
  randomtp:
    description: for random tp within a range
  clreff:
    description: used to clear potion effects
    aliases: cleareffect
  ranks:
    description: for listing the avaliable ranks
    aliases: rank
  switchtp:
    description: for switch two players around
    aliases: stp
permissions:
    frog.*:
        description: Gives access to all frog commands
        children:
            frog.time.*: true
            frog.who.*: true
            frog.gamemode.*: true
            frog.platform.*: true
            frog.promo.*: true
            frog.chat.*: true
            frog.world.*: true
            frog.pos.*: true
            frog.spleef.*: true
            frog.ban.*: true
            frog.announce: true
            frog.blocks.banned: true
            frog.zombie.protect: true
            frog.gamespawn: true
            frog.filter.*: true
            frog.chests: true
            frog.tp.*: true
        default: op
    frog.time.*:
        children:
            frog.time.dawn: true
            frog.time.day: true
            frog.time.noon: true
            frog.time.dusk: true
            frog.time.night: true
        description: all time commands
        default: false
    frog.who.*:
        children:
            frog.who.who: true
            frog.who.info: true
            frog.who.world: true
        default: false
    frog.gamemode.*:
        children:
            frog.gamemode.self: true
            frog.gamemode.other: true
        default: false
    frog.platform.*:
        children:
            frog.platform.single: true
            frog.platform.toggle: true
            frog.platform.other: true
        default: false
    frog.world.*:
        children:
            frog.world.self: true
            frog.world.other: true
        default: false
    frog.pos.*:
        children:
            frog.pos.self: true
            frog.pos.other: true
        default: false
    frog.spleef.*:
        children:
            frog.spleef.layer: true
        default: false
    frog.ban.*:
        children:
            frog.ban.kick: true
            frog.ban.tempban: true
            frog.ban.permban: true
        default: false
    frog.chat.*:
        children:
            frog.chat.me: true
            frog.chat.open: true
            frog.chat.pms: true
            frog.chat.rainbow: true
        default: false
    frog.filter.*:
        children:
            frog.filter.bypass: true
            frog.filter.notify: true
            frog.filter.add: true
            frog.filter.remove: true
            frog.filter.list: true
        default: false
    frog.tp.*:
        children:
            frog.tp.switch: true
            frog.tp.random: true
        default: false

    frog.time.dawn:
        description: dawn command
        default: false
    frog.time.day:
        description: day command
        default: false
    frog.time.noon:
        description: noon command
        default: false
    frog.time.dusk:
        description: dusk command
        default: false
    frog.time.night:
        description: night command
        default: false

    frog.who.who:
        description: who command
        default: true
    frog.who.info:
        description: complex who with info on all players
        default: false
    frog.who.world:
        description: shows worlds players are in
        default: false

    frog.gamemode.self:
        description: /gm
        default: false
    frog.gamemode.other:
        description: /gm <name>
        default: false

    frog.platform.single:
        description: creates a block of glass below your feet
        default: false

    frog.promo.*:
        description: all promos
        default: false
        
    frog.world.self:
        description: handles /world
        default: false
    frog.world.other:
        description: handles /world name
        default: false

    frog.pos.self:
        description: /pos command
        default: false
    frog.pos.other:
        description: /pos name
        default: false

    frog.spleef.layer:
        description: /spleeflayer command
        default: false

    frog.ban.kick:
        description: /kick command
        default: false
    frog.ban.tempban:
        description: /tempban command
        default: false
    frog.ban.permban:
        description: /permban command
        default: false

    frog.chat.me:
        description: chat formatting
        default: false
    frog.chat.open:
        description: chat formatting
        default: false
    frog.chat.pms:
        description: chat formatting
        default: false
    frog.chat.rainbow:
        description: chat formatting
        default: false
        
    frog.announce:
        description: /announce
        default: false
        
    frog.blocks.banned:
        description: handles (currently hardcoded)banned blocks
        default: false
        
    frog.zombie.protect:
        description: protects zombies
        default: false
        
    frog.gamespawn:
        description: for setting temporary spawns
        default: false
    
    frog.filter.bypass:
        description: for chat filter bypassing
        default: false
    frog.filter.notify:
        description: for notifying admins of people attempting to bypass the chat filter
        default: false
    frog.filter.add:
        description: for adding words to the chat filter.
        default: false
    frog.filter.remove:
        description: for removing words from the filter
        default: false
    frog.filter.list:
        description: for listing all filtered words
        default: false
        
    frog.chests:
        description: for random chests
        default: false
    
    frog.tp.switch:
        description: for switching players
        default: false
    frog.tp.random:
        description: randomtp permission
        default: false