package com.frogman786.froggles.utils;

import java.util.Random;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class rChest {
	public static ItemStack[] getRandomContents(int tier){
		ItemStack[] finalchest = new ItemStack[27];
		ItemStack[] tierg = null;
		ItemStack[] tier1 = {new ItemStack(Material.WOOD_AXE, 1),
				new ItemStack(Material.WOOD_SWORD, 1),
				new ItemStack(Material.LEATHER_BOOTS, 1),
				new ItemStack(Material.LEATHER_CHESTPLATE, 1),
				new ItemStack(Material.LEATHER_HELMET, 1),
				new ItemStack(Material.LEATHER_LEGGINGS, 1),
				new ItemStack(Material.WOOD_AXE, 1),
				new ItemStack(Material.WOOD_SWORD, 1),
				new ItemStack(Material.WOOD_AXE, 1),
				new ItemStack(Material.WOOD_AXE, 1),
				new ItemStack(Material.WOOD_SWORD, 1),
				new ItemStack(Material.LEATHER_BOOTS, 1),
				new ItemStack(Material.LEATHER_CHESTPLATE, 1),
				new ItemStack(Material.LEATHER_HELMET, 1),
				new ItemStack(Material.LEATHER_LEGGINGS, 1),
				new ItemStack(Material.STONE_AXE, 1),
				new ItemStack(Material.STONE_AXE, 1),
				new ItemStack(Material.STONE_AXE, 1),
				new ItemStack(Material.CHAINMAIL_BOOTS, 1),
				new ItemStack(Material.CHAINMAIL_LEGGINGS, 1),
				new ItemStack(Material.FLINT, 1),
				new ItemStack(Material.FLINT, 2),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.EXP_BOTTLE, 1),
				new ItemStack(Material.EXP_BOTTLE, 1),
				new ItemStack(Material.CARROT_ITEM, 1),
				new ItemStack(Material.RAW_BEEF, 1),
				new ItemStack(Material.RAW_BEEF, 1),
				new ItemStack(Material.PORK, 1),
				new ItemStack(Material.PORK, 2),
				new ItemStack(Material.PORK, 3),
				new ItemStack(Material.STICK, 1),
				new ItemStack(Material.STICK, 1),
				new ItemStack(Material.STICK, 2),
				new ItemStack(Material.STICK, 2),
				new ItemStack(Material.WHEAT, 2),
				new ItemStack(Material.WHEAT, 3),
				new ItemStack(Material.BREAD, 1),
				new ItemStack(Material.STRING, 2),
				new ItemStack(Material.FEATHER, 1),
				new ItemStack(Material.FEATHER, 2),
				new ItemStack(Material.ENDER_PEARL, 1),
				new ItemStack(Material.ENDER_PEARL, 2),
				new ItemStack(Material.POTATO_ITEM, 2),
				new ItemStack(Material.RAW_FISH, 1),
				new ItemStack(Material.ARROW, 1),
				new ItemStack(Material.ARROW, 3),
				new ItemStack(Material.ARROW, 4)};
		ItemStack[] tier2 = {new ItemStack(Material.CHAINMAIL_BOOTS, 1),
				new ItemStack(Material.CHAINMAIL_BOOTS, 1),
				new ItemStack(Material.CHAINMAIL_CHESTPLATE, 1),
				new ItemStack(Material.CHAINMAIL_CHESTPLATE, 1),
				new ItemStack(Material.CHAINMAIL_LEGGINGS, 1),
				new ItemStack(Material.CHAINMAIL_LEGGINGS, 1),
				new ItemStack(Material.CHAINMAIL_HELMET, 1),
				new ItemStack(Material.CHAINMAIL_HELMET, 1),
				new ItemStack(Material.IRON_BOOTS, 1),
				new ItemStack(Material.IRON_CHESTPLATE, 1),
				new ItemStack(Material.IRON_LEGGINGS, 1),
				new ItemStack(Material.IRON_HELMET, 1),
				new ItemStack(Material.IRON_SWORD, 1),
				new ItemStack(Material.STONE_SWORD, 1),
				new ItemStack(Material.STONE_SWORD, 1),
				new ItemStack(Material.STONE_SWORD, 1),
				new ItemStack(Material.STONE_SWORD, 1),
				new ItemStack(Material.WOOD_AXE, 1),
				new ItemStack(Material.STONE_AXE, 1),
				new ItemStack(Material.IRON_AXE, 1),
				new ItemStack(Material.IRON_AXE, 1),
				new ItemStack(Material.IRON_INGOT, 2),
				new ItemStack(Material.IRON_INGOT, 2),
				new ItemStack(Material.IRON_INGOT, 1),
				new ItemStack(Material.DIAMOND, 1),
				new ItemStack(Material.DIAMOND, 1),
				new ItemStack(Material.GOLDEN_APPLE, 1),
				new ItemStack(Material.GOLDEN_APPLE, 1),
				new ItemStack(Material.GOLDEN_APPLE, 2),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.STICK, 2),
				new ItemStack(Material.PORK, 2),
				new ItemStack(Material.COOKED_BEEF, 2),
				new ItemStack(Material.ENDER_PEARL, 2),
				new ItemStack(Material.ENDER_PEARL, 3),
				new ItemStack(Material.COOKED_CHICKEN, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.APPLE, 3),
				new ItemStack(Material.POTION, 1, Short.parseShort("8194")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16417")),
				new ItemStack(Material.POTION, 1, Short.parseShort("8261")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16453")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16460")),
				new ItemStack(Material.POTION, 1, Short.parseShort("8233")),
				new ItemStack(Material.POTION, 1, Short.parseShort("8201")),
				new ItemStack(Material.ARROW, 1),
				new ItemStack(Material.ARROW, 2),
				new ItemStack(Material.ARROW, 3),
				new ItemStack(Material.ARROW, 5),
				new ItemStack(Material.ARROW, 4),
				new ItemStack(Material.ARROW, 5)};
		ItemStack[] tier3 = {new ItemStack(Material.IRON_SWORD, 1),
				new ItemStack(Material.IRON_SWORD, 1),
				new ItemStack(Material.IRON_SWORD, 1),
				new ItemStack(Material.IRON_SWORD, 1),
				new ItemStack(Material.IRON_SWORD, 1),
				new ItemStack(Material.DIAMOND_SWORD, 1),
				new ItemStack(Material.DIAMOND_SWORD, 1),
				new ItemStack(Material.IRON_AXE, 1),
				new ItemStack(Material.IRON_AXE, 1),
				new ItemStack(Material.DIAMOND_AXE, 1),
				new ItemStack(Material.DIAMOND_AXE, 1),
				new ItemStack(Material.DIAMOND_AXE, 1),
				new ItemStack(Material.DIAMOND_AXE, 1),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.BOW, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.FISHING_ROD, 1),
				new ItemStack(Material.IRON_BOOTS, 1),
				new ItemStack(Material.IRON_BOOTS, 1),
				new ItemStack(Material.IRON_BOOTS, 1),
				new ItemStack(Material.IRON_CHESTPLATE, 1),
				new ItemStack(Material.IRON_CHESTPLATE, 1),
				new ItemStack(Material.IRON_CHESTPLATE, 1),
				new ItemStack(Material.IRON_LEGGINGS, 1),
				new ItemStack(Material.IRON_LEGGINGS, 1),
				new ItemStack(Material.IRON_LEGGINGS, 1),
				new ItemStack(Material.IRON_HELMET, 1),
				new ItemStack(Material.IRON_HELMET, 1),
				new ItemStack(Material.IRON_HELMET, 1),
				new ItemStack(Material.DIAMOND_BOOTS, 1),
				new ItemStack(Material.DIAMOND_CHESTPLATE, 1),
				new ItemStack(Material.DIAMOND_HELMET, 1),
				new ItemStack(Material.DIAMOND_LEGGINGS, 1),
				new ItemStack(Material.APPLE, 3),
				new ItemStack(Material.COOKED_BEEF, 3),
				new ItemStack(Material.COOKED_CHICKEN, 2),
				new ItemStack(Material.COOKED_CHICKEN, 3),
				new ItemStack(Material.PORK, 3),
				new ItemStack(Material.GOLDEN_APPLE, 3),
				new ItemStack(Material.GOLDEN_APPLE, 3),
				new ItemStack(Material.GOLDEN_APPLE, 5),
				new ItemStack(Material.POTION, 1, Short.parseShort("8225")),
				new ItemStack(Material.POTION, 1, Short.parseShort("8226")),
				new ItemStack(Material.POTION, 1, Short.parseShort("8229")),
				new ItemStack(Material.POTION, 1, Short.parseShort("8233")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16420")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16421")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16421")),
				new ItemStack(Material.POTION, 1, Short.parseShort("16428")),
				new ItemStack(Material.ARROW, 7)};

		if(tier==1){
			tierg = tier1;
		}
		if(tier==2){
			tierg = tier2;
		}
		if(tier==3){
			tierg = tier3;
		}
		Random rand = new Random();
	    int randomAmmount = rand.nextInt((8 - 0) + 1) + 0;
	    for(int i=0;i<randomAmmount;i++){
		    int randomSlot = rand.nextInt((26 - 0) + 1) + 0;
		    int randomItem = rand.nextInt((tierg.length - 0) + 1) + 0;
		    finalchest[randomSlot] = tierg[randomItem];
	    }
		return finalchest;
		
	}
}
